rewarding/urls.py
from django.urls import path
from django.contrib.auth.decorators import permission_required

from ikwen.rewarding.views import Configuration, ChangeCoupon, Dashboard, CouponDetail, upload_coupon_image

urlpatterns = [
    path('dashboard/', permission_required('rewarding.ik_manage_rewarding')(Dashboard.as_view()), name='dashboard'),
    path('configuration/', permission_required('rewarding.ik_manage_rewarding')(Configuration.as_view()), name='configuration'),
    path('changeCoupon/', permission_required('rewarding.ik_manage_rewarding')(ChangeCoupon.as_view()), name='change_coupon'),
    path('changeCoupon/<object_id>)/', permission_required('rewarding.ik_manage_rewarding')(ChangeCoupon.as_view()), name='change_coupon'),
    path('upload_coupon_image', upload_coupon_image, name='upload_coupon_image'),
    path('coupon_detail', CouponDetail.as_view(), name='coupon_detail'),
]

rewarding/models.py
from threading import Thread

from django.conf import settings
from django.db.models.signals import post_save
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from djongo import models

from ikwen.conf.settings import IKWEN_SERVICE_ID as UMBRELLA_SERVICE_ID
from ikwen.accesscontrol.backends import UMBRELLA
from ikwen.core.models import AbstractWatchModel, Model, Service
from ikwen.core.utils import get_service_instance, to_dict
from ikwen.accesscontrol.models import Member

WELCOME = 'Welcome'
PURCHASE = 'Purchase'
REWARD_PACK_OFFER = 'RewardPackOffer'
FREE_REWARD_OFFERED = 'FreeRewardOffered'
WELCOME_REWARD_OFFERED = 'WelcomeRewardOffered'
PAYMENT_REWARD_OFFERED = 'PaymentRewardOffered'
MANUAL_REWARD_OFFERED = 'ManualRewardOffered'
REFERRAL_REWARD_OFFERED = 'ReferralRewardOffered'


class Coupon(AbstractWatchModel):
    """
    A coupon that a Member may collect
    to obtain a concrete Ticket
    """
    UPLOAD_TO = 'rewarding/coupons'
    MEDIA_UPLOAD_TO = 'rewarding/media'
    DISCOUNT = 'Discount'
    PURCHASE_ORDER = 'PurchaseOrder'
    GIFT = 'Gift'
    DOWNLOAD = 'Download'
    TYPE_CHOICES = (
        (DISCOUNT, _("Discount")),
        (PURCHASE_ORDER, _("Purchase Order")),
        (GIFT, _("Gift")),
        (DOWNLOAD, _("Download")),
    )

    PENDING_FOR_APPROVAL = 'PendingForApproval'
    APPROVED = 'Approved'
    REJECTED = 'Rejected'
    STATUS_CHOICES = (
        (PENDING_FOR_APPROVAL, _("Pending for approval")),
        (APPROVED, _("Approved")),
        (REJECTED, _("Rejected")),
    )

    service = models.ForeignKey(Service, default=get_service_instance, related_name='+', on_delete=models.CASCADE)
    name = models.CharField(max_length=60, db_index=True,
                            help_text=_("Name of the coupon"))
    slug = models.SlugField()
    image = models.ImageField(upload_to=UPLOAD_TO, blank=True, null=True)
    media = models.FileField(upload_to=MEDIA_UPLOAD_TO, blank=True, null=True, editable=False,
                             help_text=_("If this coupon gives access to download a media, upload the media file."))
    type = models.CharField(max_length=30, choices=TYPE_CHOICES)
    rate = models.IntegerField(default=0,
                               help_text=_("Discount rate value if coupon is of type Discount."))
    status = models.CharField(max_length=30, choices=STATUS_CHOICES,
                              default=PENDING_FOR_APPROVAL, db_index=True)
    description = models.TextField()
    coefficient = models.IntegerField(default=1, db_index=True)
    heap_size = models.IntegerField(db_index=True, default=100,
                                    help_text="How many of this coupons must "
                                              "collected to obtain a concrete Ticket")
    month_quota = models.IntegerField(help_text=_("Number of random people the system will get to reach 100 coupons "
                                                  "in the current month."))
    month_winners = models.IntegerField(default=0,
                                        help_text=_("How many winners there have been since the 1st of "
                                                    "the month."))
    is_active = models.BooleanField(default=True)
    deleted = models.BooleanField(default=False)

    offered_history = models.JSONField(editable=False)
    total_offered = models.IntegerField(default=0)

    class Meta:
        unique_together = (
            ('service', 'name'),
            ('service', 'slug'),
        )

    def __str__(self):
        return self.name

    def save(self, **kwargs):
        """
        Sets the Coupon coefficient based on its type
        and forces it to be saved in Umbrella database
        """
        if self.type == self.DISCOUNT:
            self.coefficient = 1
        elif self.type == self.GIFT:
            self.coefficient = 2
        elif self.type == self.PURCHASE_ORDER:
            self.coefficient = 3
        elif self.type == self.DOWNLOAD:
            self.coefficient = 4
        if getattr(settings, 'IKWEN_SERVICE_ID') != UMBRELLA_SERVICE_ID:
            kwargs['using'] = UMBRELLA
        super(Coupon, self).save(**kwargs)

    def to_dict(self):
        var = to_dict(self)
        try:
            del(var['coefficient'])
            del(var['month_quota'])
            del(var['month_winners'])
            del(var['offered_history'])
            del(var['total_offered'])
        except:
            pass
        return var

    def _get_join_reward_pack(self):
        try:
            return JoinRewardPack.objects.using(UMBRELLA).get(coupon=self)
        except JoinRewardPack.DoesNotExist:
            pass
    join_reward_pack = property(_get_join_reward_pack)

    def _get_referral_reward_pack(self):
        try:
            return ReferralRewardPack.objects.using(UMBRELLA).get(coupon=self)
        except ReferralRewardPack.DoesNotExist:
            pass
    referral_reward_pack = property(_get_referral_reward_pack)

    def get_payment_reward_pack(self, floor, ceiling):
        try:
            return PaymentRewardPack.objects.using(UMBRELLA).get(coupon=self, floor=floor, ceiling=ceiling)
        except PaymentRewardPack.DoesNotExist:
            pass


class Reward(Model):
    """
    A coupon reward issued by the system either
    for free of after an online payment
    """
    # Statuses
    PREPARED = 'Prepared'
    SENT = 'Sent'

    # Type of reward
    JOIN = 'Join'  # Received after joining community
    FREE = 'Free'  # Received for free
    REFERRAL = 'Referral'  # Received for getting someone to join the community
    PAYMENT = 'Payment'  # Received after online payment
    MANUAL = 'Manual'  # Received after a mission

    service = models.ForeignKey(Service, related_name='+', on_delete=models.CASCADE)
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    coupon = models.ForeignKey(Coupon, db_index=True, on_delete=models.CASCADE)
    count = models.IntegerField(default=0)
    status = models.CharField(max_length=15, default=PREPARED, db_index=True)
    type = models.CharField(max_length=15, default=FREE, db_index=True)
    object_id = models.CharField(max_length=60, blank=True, null=True, db_index=True)
    amount = models.FloatField(blank=True, null=True, db_index=True,
                               help_text="Amount that was paid to trigger the reward.")


class MemberCoupon(Model):
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    coupon = models.ForeignKey(Coupon, on_delete=models.CASCADE)

    class Meta:
        abstract = True


class CouponWinner(MemberCoupon):
    """
    Winner of a Coupon
    """
    collected = models.BooleanField(default=False)


class CumulatedCoupon(MemberCoupon):
    """
    Cumulated Coupon Rewards for a Member
    """
    count = models.IntegerField(default=0)

    class Meta:
        unique_together = ('member', 'coupon', )


class CouponSummary(Model):
    """
    Summary of coupons earned by a Member on a Service
    regardless of what coupon it is.
    """
    service = models.ForeignKey(Service, related_name='+', on_delete=models.CASCADE)
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    count = models.IntegerField(default=0)
    threshold_reached = models.BooleanField(default=False)

    class Meta:
        unique_together = ('service', 'member', )


class CouponUse(MemberCoupon):
    """
    Keeps track of how a Coupon was used
    """
    PAYMENT = "Payment"
    DONATION = "Donation"

    count = models.IntegerField(default=0)
    usage = models.CharField(max_length=30,
                             help_text="How the coupon heap was used. Either during a Payment or by donating.")
    object_id = models.CharField(max_length=30, blank=True, null=True)


class CRProfile(Model):
    """
    Member CR information on a community. This object
    is supposed to exist only in the Service's database
    and not in umbrella.
    """
    JOIN_REWARD = 1
    PAYMENT_REWARD = 2
    MANUAL_REWARD = 3
    FREE_REWARD = 4
    member = models.OneToOneField(Member, on_delete=models.CASCADE)
    reward_score = models.IntegerField(default=JOIN_REWARD, db_index=True)
    coupon_score = models.IntegerField(default=0, db_index=True)
    last_reward_date = models.DateTimeField(default=timezone.now, db_index=True)


class CRBillingPlan(Model):
    """
    Billing Plan ikwen charge Operator who
    want to launch a conf campaign
    """
    FREE_TEST = 'free-test'
    name = models.CharField(max_length=60, unique=True)
    slug = models.SlugField()
    audience_size = models.IntegerField()
    raw_monthly_cost = models.FloatField()
    sms_monthly_cost = models.FloatField()
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = "CR Billing Plans"

    def __str__(self):
        return self.name


class CROperatorProfile(AbstractWatchModel):
    service = models.OneToOneField(Service, related_name='+', on_delete=models.CASCADE)
    plan = models.ForeignKey(CRBillingPlan, db_index=True, on_delete=models.CASCADE)
    billing_cycle = models.CharField(max_length=30, blank=True,
                                     choices=Service.BILLING_CYCLES_CHOICES, default=Service.QUARTERLY)
    monthly_cost = models.FloatField(default=0, db_index=True)
    sms = models.BooleanField(default=False)
    auto_renew = models.BooleanField(default=True)
    expiry = models.DateField(db_index=True)
    is_active = models.BooleanField(default=True)

    push_history = models.JSONField()
    # We intentionally write purchaseorder instead of purchase_order: DO NOT CHANGE THAT !
    purchaseorder_history = models.JSONField()
    gift_history = models.JSONField()
    discount_history = models.JSONField()

    total_push = models.IntegerField(default=0)
    # We intentionally write purchaseorder instead of purchase_order: DO NOT CHANGE THAT !
    total_purchaseorder = models.IntegerField(default=0)

rewarding/templates/rewarding/change_coupon.html
{% extends 'core/change_object_base.html' %}
{% load i18n humanize static auth_tokens %}

{% block page_title %}
<title> {% if obj %}{{ obj.name }}{% else %}{% trans "New Card" %}{% endif %} - {{ service.project_name }} </title>
{% endblock %}

{% block head_style %}
    {{ block.super }}
    <link href="{% static 'ikwen/css/uploader-single.css' %}" media="screen" rel="stylesheet" type="text/css" />
    <style>
        .form-container {padding: 0}
        time {position: absolute; right: 20px}
        @media (max-width: 767px) {
            #admin-content > .row {margin: 0}
            #admin-content.change-form form {padding: 15px 0}
            .winners-container {padding: 0}
            .winners-title {padding: 0 15px}
            .member {height: 81px}
        }
        @media (min-width: 768px) {
            .winners-container {margin-left: -15px}
            #admin-content .member .info {
                max-width: 290px;
            }
            .member {height: 70px}
            .member .photo {
                border-radius: 23px;
                height: 46px;
                width: 46px;
            }
        }
        @media (max-width: 991px) {
            .winners-container {margin-top: 15px}
        }
        @media (min-width: 992px) {
            .admin-form .form-control:not([type=checkbox]) {
                width: 360px;
            }
            #admin-content .member .info {
                max-width: 290px;
            }
        }
        @media (min-width: 1200px) {
            .admin-form .form-control:not([type=checkbox]) {
                width: 400px;
            }
            #admin-content .member .info {
                max-width: 360px;
            }
        }
    </style>
{% endblock %}
{% block head_js %}
    {{ block.super }}
    <script src="{% static 'ikwen/ajaxuploader/js/fileuploader.js' %}"></script>
{% endblock %}

{% block breadcrumb_location %}
    <li>
        <a href="{{ object_list_url }}">{{ verbose_name_plural|capfirst }}</a>
    </li>
    {% if obj %}
        <li>{{ obj }}</li>
    {% else %}
        <li>{% trans 'New Coupon' %}</li>
    {% endif %}
{% endblock %}

{% block admin_content %}
    <div id="admin-content" class="change-form">
        <div class="row">
            <div class="col-sm-6 form-container">
                {% if errors %}<p class="alert alert-danger">{{ errors }}</p>{% endif %}
                <form class="admin-form" method="post">{% csrf_token %}
                    <input type="hidden" name="image_url" id="image_url" value="{% if obj.image.name %}{{ obj.image.url }}{% endif %}" />
                    <div class="container-fluid">
                        {% include 'core/snippets/model_admin_form.html' %}
                        {% with image=obj.image img_help_text='Card image: 400px x 600px' %}
                            {% include 'rewarding/snippets/uploader_single.html' %}
                        {% endwith %}
                        <div class="form-group col-xs-12 col-sm-8 col-md-6" style="clear: both; padding-top: 15px">
                            <button class="btn btn-sm btn-primary btn-block">{% trans "Save" %}</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-sm-6 winners-container">
                <div class="winners-title">
                    <h3>Happles</h3>
                    <p class="text-muted" style="margin-top: -10px">{% trans "People having collected 100 coupons or more." %}</p>
                </div>
                <ul class="people object-list" style="margin: 0; padding: 0">
                {% for member in winner_list %}
                    <li id="{{ member.id }}" class="member {{ member.get_status }}" data-id="{{ member.id }}">
                        {% url 'ikwen:profile' member.id as member_url %}
                        <time>{{ member.date_joined|date }}</time>
                        {% if member.photo and member.photo.name %}
                            <a href="{{ member_url|ikwenize }}" class="photo" style="background-image: url({{ settings.IKWEN_MEDIA_URL }}{{ member.photo.small_name }})"></a>
                        {% else %}
                            <a href="{{ member_url|ikwenize }}" class="photo" style="background-image: url({% static 'ikwen/img/login-avatar.jpg' %})"></a>
                        {% endif %}
                        <div class="info">
                            <a href="{{ member_url|ikwenize }}" class="full_name">{{ member.full_name }}</a>
                            <p class="about">{{ member.phone }}, {{ member.email }}</p>
                        </div>
                    </li>
                {% empty %}
                    <li style="border: 1px solid #03A9F4; border-radius: 3px; display: inline-block; padding: 15px">
                        <div>
                            {% trans "No winner for now" %}
                        </div>
                        <p>{% blocktrans %}
                            <em class="text-muted">You must set a <b>Month quota</b> bigger than 0.</em>
                            <a class="set-month-quota" href="javascript:;">Set now</a>
                        {% endblocktrans %}</p>
                    </li>
                {% endfor %}
                </ul>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script>
        (function() {
            $('.set-month-quota').click(function() {
                $('.field-month_quota').addClass('failure');
                $('#id_month_quota').focus();
            })
        })()
    </script>
{% endblock %}

rewarding/templates/rewarding/dashboard.html
{% extends "core/app_base_admin.html" %}
{% load i18n humanize static admin_list %}

{% block page_title %}
<title>{% trans "Dashboard" %} - {% trans "Continuous Rewarding" %} - ikwen </title>
{% endblock %}

{% block head_style %}
    {{ block.super }}
    <link rel='stylesheet' href="{% static 'ikwen/css/dashboard.css' %}" />
    <link href="{% static 'rewarding/css/rewarding.css' %}" media="screen" rel="stylesheet" type="text/css" />
{% endblock %}

{% block head_js %}
    {{ block.super }}
    <script src="{% static 'ikwen/swiper/js/swiper.jquery.min.js' %}"></script>
{% endblock %}

{% block breadcrumb_location %}
    <li>
        <a href="{% url 'rewarding:configuration' %}">{% trans "Continuous Rewarding" %}</a>
    </li>
    <li>{% trans "Dashboard" %}</li>
{% endblock %}

{% block admin_content %}
    <div id="admin-content">
        <div class="container-fluid">
            <div class="section-title perf">
                <div>
                    <h4 style="float: left">{% trans "Performances" %}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-</h4>
                    <div class="dropdown" style="cursor: pointer; float: left; margin: 13px 0 0 15px">
                        <span class="dropdown-toggle" id="period" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                            <span class="target">{% trans "Today" %}</span>
                            <span class="caret"></span>
                        </span>
                        <ul id="performances-period" class="dropdown-menu" aria-labelledby="period">
                            <li data-target="today" style="display: none"><a>{% trans "Today" %}</a></li>
                            <li data-target="yesterday"><a>{% trans "Yesterday" %}</a></li>
                            <li data-target="last_week"><a>{% trans "Last week" %}</a></li>
                            <li data-target="last_28_days"><a>{% trans "Last 28 days" %}</a></li>
                        </ul>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="row performances" style="clear: both">
                <div class="col-sm-6">
                    <div class="push-report">
                        <header>
                            <h5>{% trans "Pushes" %}</h5>
                            <div class="clear"></div>
                        </header>
                        <div class="row">
                            <div class="col-xs-6">
                                <div>{% trans "Sent" %}</div>
                                <div>
                                    <em class="report today">487</em>
                                    <em class="report yesterday tpl">{{ orders_report.yesterday.count|intcomma }}</em>
                                    <em class="report last_week tpl">{{ orders_report.last_week.count|intcomma }}</em>
                                    <em class="report last_28_days tpl">{{ orders_report.last_28_days.count|intcomma }}</em>
                                </div>
                            </div>
                            <div class="col-xs-6">
                                <div>{% trans "Views" %}</div>
                                <div>
                                    <em class="report today">
                                        <span class="count">432</span>
                                        <span class="ratio">83.1%</span>
                                    </em>
                                    <em class="report yesterday tpl">{{ orders_report.yesterday.count|intcomma }}</em>
                                    <em class="report last_week tpl">{{ orders_report.last_week.count|intcomma }}</em>
                                    <em class="report last_28_days tpl">{{ orders_report.last_28_days.count|intcomma }}</em>
                                </div>
                            </div>
                        </div>
                        <div>
                            <div>
                                <label>{% trans "By Mail" %} :</label>
                                <span class="text-muted">47</span>
                            </div>
                            <div>
                                <label>{% trans "By SMS" %} :</label>
                                <span class="text-muted" style="padding-right: 15px">0</span>
                                <a href="{% url 'rewarding:configuration' %}">{% trans "Activate SMS" %}</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div>
                        <header>
                            <h5>{% trans "ACPP" %} <i class="text-muted">({% trans "Avg. Card Per Push" %})</i></h5>
                            <div class="clear"></div>
                        </header>
                        <div style="padding-top: 3px">
                            <p>
                                <label>{% trans "Discounts" %}:</label>
                                <span class="text-muted">0</span>
                            </p>
                            <p>
                                <label>{% trans "Purchase Orders" %}:</label>
                                <span class="text-muted">0</span>
                            </p>
                            <p>
                                <label>{% trans "Gifts" %}:</label>
                                <span class="text-muted">0</span>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div id="chart-stage">
                <div class="btn-group pull-right" role="group" aria-label="...">
                    <button type="button" class="btn btn-sm btn-default active">{% trans "Week" %}</button>
                    <button type="button" class="btn btn-sm btn-default">{% trans "Month" %}</button>
                </div>
                <div class="chart"></div>
            </div>
        </div>
    </div>
{% endblock %}